import type {Metadata} from "next";
import {Inter} from "next/font/google";
// import "./globals.scss";
import {TheFooter} from "@/components/TheFooter/TheFooter";
import {LoggedInHeader} from "@/components/LoggedInHeader/LoggedInHeader";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Find Flight",
    description: "Generated by create next app",
};

export default function GeneralLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <LoggedInHeader/>

        <main>
            {children}
        </main>
        {/*<TheFooter/>*/}
        </body>
        </html>
    );
}
